# Generated by Django 6.0.5 on 2026-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('fdm', 'FDM'), ('resin', 'Resin'), ('sls', 'SLS')], max_length=10)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('printing', 'Printing'), ('error', 'Error')], default='offline', max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
